from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import httpx
import pytest

from national_gallery_api import client as client_module

DATA_DIR = Path(__file__).parent / "data"


def load_source(name: str) -> dict[str, Any]:
    """These files are regenerated by `tests/data/_capture.py` -- don't edit by hand."""
    return json.loads((DATA_DIR / f"{name}.json").read_text())


PERSON_SOURCE = load_source("person")
ORGANISATION_SOURCE = load_source("organisation")
WORK_SOURCE = load_source("work")
CONCEPT_SOURCE = load_source("concept")
PLACE_SOURCE = load_source("place")
EVENT_SOURCE = load_source("event")
EXHIBITION_SOURCE = load_source("exhibition")
LOCATION_SOURCE = load_source("location")
PUBLICATION_SOURCE = load_source("publication")
ARCHIVE_SOURCE = load_source("archive")
MEDIA_SOURCE = load_source("media")
PACKAGE_SOURCE = load_source("package")


def pid_of(source: dict[str, Any]) -> str | None:
    """The PID identifier value of a document (mirrors `Entity.pid`)."""
    return next((i["value"] for i in source.get("identifier", []) if i.get("type") == "PID"), None)


def identifier_of(source: dict[str, Any], type_: str) -> str | None:
    """The first identifier value of a given type (e.g. ``"object number"``)."""
    return next((i["value"] for i in source.get("identifier", []) if i.get("type") == type_), None)


def value_list(entries: list[dict[str, Any]]) -> list[str]:
    """The non-empty `value` of each entry (mirrors `name`/`term`/... accessors)."""
    return [e["value"] for e in entries if e.get("value")]


def titles_of(refs: list[dict[str, Any]]) -> list[str]:
    """The `summary.title` of each reference (mirrors `makers`/`venues`/... accessors)."""
    return [r["summary"]["title"] for r in refs if isinstance(r.get("summary"), dict) and r["summary"].get("title")]


def named_value(named_entries: list[dict[str, Any]]) -> str | None:
    """The first `name[].value` of the first entry (mirrors the `Named.name` accessor)."""
    if not named_entries:
        return None
    return value_list(named_entries[0].get("name", []))[0]


def es_payload(
    sources: list[dict[str, Any]],
    *,
    total: int | None = None,
    relation: str = "eq",
    aggregations: dict[str, Any] | None = None,
    sorts: list[list[Any]] | None = None,
) -> dict[str, Any]:
    """Wrap `_source` documents in an Elasticsearch-shaped response body.

    `sorts`, when given, sets each hit's top-level `sort` array (what
    `iter_all` reads to page with `search_after`).
    """
    hits = []
    for i, source in enumerate(sources):
        hit: dict[str, Any] = {"_source": source}
        if sorts is not None:
            hit["sort"] = sorts[i]
        hits.append(hit)
    payload: dict[str, Any] = {
        "hits": {
            "total": {"value": len(sources) if total is None else total, "relation": relation},
            "hits": hits,
        }
    }
    if aggregations is not None:
        payload["aggregations"] = aggregations
    return payload


class MockAPI:
    """Records request bodies and serves whatever the test's `respond` returns."""

    def __init__(self) -> None:
        self.requests: list[dict[str, Any]] = []
        # Default: every request gets an empty result set. Tests override this.
        self.respond: Callable[[dict[str, Any]], httpx.Response] = lambda body: httpx.Response(
            200, json=es_payload([])
        )

    def __call__(self, request: httpx.Request) -> httpx.Response:
        body = json.loads(request.content)
        self.requests.append(body)
        return self.respond(body)

    @property
    def last_request(self) -> dict[str, Any]:
        return self.requests[-1]

    def reply_once_with(self, payloads: list[dict[str, Any]]) -> None:
        """Serve `payloads` in order across successive requests (for paging)."""
        queue = list(payloads)

        def respond(_body: dict[str, Any]) -> httpx.Response:
            payload = queue.pop(0) if queue else es_payload([])
            return httpx.Response(200, json=payload)

        self.respond = respond


@pytest.fixture
def mock_api(monkeypatch: pytest.MonkeyPatch) -> MockAPI:
    """Route both sync and async clients through an in-process MockTransport."""
    api = MockAPI()
    transport = httpx.MockTransport(api)
    monkeypatch.setattr(client_module, "build_sync_transport", lambda **_kw: transport)
    monkeypatch.setattr(client_module, "build_async_transport", lambda **_kw: transport)
    return api


@pytest.fixture(scope="module")
def vcr_config() -> dict[str, Any]:
    """Config for `@pytest.mark.vcr` (pytest-recording).

    Cassettes record real API traffic on first run and replay it offline after. Every call POSTs to the same
    `/_search` URL and differs only in the JSON body, so `body` must be in `match_on` or VCR would replay the first
    recorded response for every request.
    """
    return {
        "match_on": ["method", "scheme", "host", "path", "body"],
        "record_mode": "once",  # record if absent, replay if present, error on new requests
        "decode_compressed_response": True,  # store readable JSON, not gzip
    }
